At cache projects
tighten/ozzie pull request #54
Opened 2020-09-17 21:44 UTC by mattstauffer

Duplicate of #7, which GitHub won't let me re-open now that we renamed the master branch.

There are notes in there that need to be acted on.

2020-09-24 22:06 UTC, jakebathman commented
@mattstauffer Since you created this PR I can't tag you for review, but it's ready to look at again.

2020-09-27 02:12 UTC, jakebathman requested changes
Things I noticed while re-reviewing (and pointed out in #59)

2020-09-27 02:12 UTC, jakebathman commented on README.md
> +The scores and info for each project are cached no more than daily using the `snapshot:today` command. This can be run manually, but is scheduled to run daily. Make sure to run the scheduler when dep
```suggestion
The scores and info for each project are snapshotted daily using the `snapshot:today` command. This can be run manually, but is scheduled to run daily. Make sure to run the scheduler when deployed.
```

2020-09-27 02:12 UTC, jakebathman commented on README.md
> +Updating this cache manually using the `-f` flag to force all project data to be updated for today's date:
```suggestion
To update daily snapshots for all projects, use the `-f` flag:
```

2020-09-27 02:12 UTC, jakebathman commented on app/Snapshot.php
> +        return $query->whereDate('created_at', '=', now()->format('Y-m-d'));
Should be `snapshot_date` instead.

```suggestion
        return $query->whereDate('snapshot_date', '=', now()->format('Y-m-d'));
```

2020-09-28 01:23 UTC, mattstauffer commented on database/migrations/2018_04_20_172748_create_snapshots_table.php
> +            $table->string('snapshot_date');
Any reason this is a string instead of a date?

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +class CreateProjectSnapshot extends Command
Should this be plural since it's running for all projects?

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +            $project = new Project($project->namespace, $project->name, $project->maintainers);
Is this a pattern we do a lot? Should we consider a `fromJson` static constructor?

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +            $this->updateProgress($project->name);
Maybe `updateProgressBar` so it's clearer?

2020-09-28 01:23 UTC, mattstauffer commented on README.md
> +Projects are currently stored in a JSON file, `projects.json` in the root directory.
```suggestion
The list of projects is currently stored in a JSON file, `projects.json`, in the root directory.
```

2020-09-28 01:23 UTC, mattstauffer commented on README.md
> +The scores and info for each project are snapshotted daily using the `snapshot:today` command. This can be run manually, but is scheduled to run daily. Make sure to run the scheduler when deployed.
```suggestion
The scores for each project are recorded in a daily snapshot (for historical comparison) using the `snapshot:today` command. This can be run manually, but it's also scheduled to run daily. Make sure to [set up the scheduler cron job](https://laravel.com/docs/scheduling) on any server where this project is deployed.
```

2020-09-28 01:23 UTC, mattstauffer commented on README.md
> +To update daily snapshots for all projects, use the `-f` flag:
```suggestion
By default re-running the command will not update the day's existing snapshots. To override this behavior, use the `-f` flag, which will create any missing snapshots for the day and update all existing snapshots.
```

2020-09-28 01:23 UTC, mattstauffer commented on README.md
> +This does not create a new snapshot for the day; any existing project data for today is updated, and missing projects have a new snapshot created.
Can delete this paragraph because of the update I suggested above

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +    protected $signature = 'snapshot:today {--f|force : Snapshot all projects, updating any existing data for today}';
```suggestion
    protected $signature = 'snapshot:today {--f|force : Force an update of any snapshots captured today}';
```

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +    protected $description = 'Create a snapshot of the current status of all GitHub projects.';
```suggestion
    protected $description = 'Create a snapshot of the current status of all projects' scores.';
```

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +        $projects = $this->getProjectsToSnapshot();
```suggestion
        $projects = $this->getProjectsToSnapshot();
```

No need for that comment

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +                    'snapshot_date' => now()->format('Y-m-d'),
Once this is a `date` object I think you can just pass `now()` to it

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +    protected function getProjectsToSnapshot()
Mind dropping `get` from this one?

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +            // Return the full list of projects without filtering
```suggestion
            // Require updating for all projects, whether or not they've already had a snapshot captured today
```

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +    protected function updateProgress($current = null)
Would we ever have `null` passed in here?

2020-09-28 01:23 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshot.php
> +            $this->line("... {$current}");
This is a nice touch!

2020-09-28 01:27 UTC, mattstauffer commented
Great work, @jakebathman, thank you so much!!!

2020-09-28 21:55 UTC, jakebathman commented on app/Console/Commands/CreateProjectSnapshot.php
> +            $project = new Project($project->namespace, $project->name, $project->maintainers);
It's common enough, but refactoring `Project` to be an eloquent model after this PR will make this pattern obsolete.

2020-09-28 22:13 UTC, jakebathman commented on app/Console/Commands/CreateProjectSnapshot.php
> +                    'snapshot_date' => now()->format('Y-m-d'),
This actually doesn't work for some reason. Looking at `Query\Builder`, there doesn't seem to be any place that the model's casts are used. `updateOrCreate`'s baseline is just making a set of `where` queries with the first array.

2020-09-28 22:28 UTC, jakebathman approved these changes
Good to merge as far as I'm concerned.

2020-09-29 01:20 UTC, merged

2020-09-29 01:20 UTC, mattstauffer commented
Thank you so much for finishing this up @jakebathman!