Change Projects to be managed in MySQL
tighten/ozzie pull request #72
Opened 2020-10-12 18:40 UTC by jakebathman

## Overview

This PR changes the way that projects are stored and managed in Ozzie. Until now, the canonical place that projects were listed is `projects.json` in the root. GitHub stats were stored in cache and updated synchronously with the first dashboard load. Lots of projects would make this request very long (or, [with many projects, 500](https://twitter.com/alex_/status/1314286096331702274)).

With this pull request, this `projects.json` file (or `projects.json.dist` by default for Tighten projects) is only used as a first-time seed of project data to the new `projects` table. From there, stats are populated every hour via the artisan command `stats:fetch` and stored in that same table.

Snapshots now use these data from the `projects` table as well, storing snapshots instantly to the `snapshots` table daily using the `stats:snapshot` command.

Here's what the `projects` table structure looks like now:

| id | namespace | name    | maintainers        | issues_count | pull_requests_count | issues | pull_requests | created_at | updated_at |
|----|-----------|---------|--------------------|--------------|---------------------|------|---------------|---------------------|---------------------|
|  2 | tighten   | collect | ["jamisonvalenta"] |            6 |                   0 | [{issues_json}] | [{prs_json}]            | 2020-10-09 20:11:31 | 2020-10-09 20:11:47 |

⚠️ This PR requires a migration to the `snapshots` table, and adds a new table `projects`:

```sql
-- CreateProjectsTable
CREATE TABLE `projects` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `namespace` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `maintainers` text NOT NULL,
  `issues_count` int unsigned NULL DEFAULT '0',
  `pull_requests_count` int unsigned NULL DEFAULT '0',
  `issues` longtext NULL,
  `pull_requests` longtext NULL,
  `created_at` timestamp NULL,
  `updated_at` timestamp NULL)
DEFAULT CHARACTER SET utf8mb4 COLLATE 'utf8mb4_unicode_ci'

-- AddProjectIdToSnapshotsTable
ALTER TABLE `snapshots`
  ADD `project_id` 
    BIGINT 
    unsigned 
    NOT NULL 
    AFTER `id`
```

## Screenshots

### `stats:fetch`

This new command is what actually pulls the data into the `projects` table.

![stats_fetch](https://user-images.githubusercontent.com/43112/95779757-36d9cf00-0c90-11eb-8f5e-b949771533ed.gif)

### `stats:snapshot` 

The renamed `snapshot:today` command, which simply snapshots the counts in `projects` instead of pulling from GitHub.

![stats_snapshot](https://user-images.githubusercontent.com/43112/95779765-3b9e8300-0c90-11eb-8280-37de7fcfaabf.gif)

### Relative update timestamp
Added relative update time for each project as subhead. If the project's stats weren't updated during the last run of `stats:fetch`, this timestamp won't change either.

<img width="748" alt="Screen Shot 2020-10-12 at 12 02 01 PM" src="https://user-images.githubusercontent.com/43112/95779792-4ce78f80-0c90-11eb-80b8-fbd0f0619a07.png">

## Detailed Changes

- Add migration for new `projects` table
- Convert `App\Project` to be an eloquent model for this table
- Refactor the methods in the old `Project` class to work with the model attributes and assume data exists in the table
- Add new command `stats:fetch` to actually pull project data and store it in the `projects` table
- Add schedule for `stats:fetch` to run hourly
- Rename `Pr` and `Prs` in many places to be `PullRequest` and `PullRequests`
- Delete the now-useless `App\Projects`
- Add relative update time to subhead of each package table in `components.project` view
- Rename snapshot command to `stats:snapshot` to match other commands
- Update readme to include info about project file and seeding
- Add `snapshots` and scoped `snapshotToday` relationships to `Project`
- Change `composer.json` to use `tighten` namespace in `name`
- Change `project_id` migration to put the field second
- Change `ProjectsSeeder` path getter to use updated optional `*.dist` file

2020-10-12 19:02 UTC, jakebathman commented
@AlexVanderbist if you get a spare minute this week, could you pull this down locally and try it out with all of the Spatie projects? 

I also like your idea in #71, we should look at that after this PR is merged. That, plus a basic CRUD page to manage projects (e.g., what if you want to hide a particular repo from Ozzie?) would probably be 99% of the functionality we'd need to ditch `projects.json` altogether.

2020-10-14 09:54 UTC, AlexVanderbist commented
@jakebathman just gave this a spin and worked great for our repos! I only ran into a weird issue with GitHub throwing a "not found" exception for this repo: https://github.com/spatie/medialibrary-demo-laracon. I think it's probably an unrelated issue. 

>I also like your idea in #71, we should look at that after this PR is merged. That, plus a basic CRUD page to manage projects (e.g., what if you want to hide a particular repo from Ozzie?) would probably be 99% of the functionality we'd need to ditch projects.json altogether.

CRUD page would be great but that adds more work to provide a way to authenticate (not that it's that much work or anything, but still). Maybe a filter callback can provide a flexible solution to excluding certain projects? E.g.
```php
Project::shouldImportRepo(function ($repo) {
    if ($repo['name'] === 'my-repo') { return false; }

    return ! $repo['archived']
})
```
Not that different from just updating the fetch command but this way merging in updates from source repository stays easy and without the risk of merge conflicts. Just an idea and happy to help implement it :)

2020-10-15 18:30 UTC, mattstauffer requested changes
Fantastic work!! Some notes here.

2020-10-15 18:30 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshots.php
>          $completedSnapshots = Snapshot::today()->get()->pluck('name');
Can we change this to pluck `project_id` instead, now that we have it? Cleaner than name?

2020-10-15 18:30 UTC, mattstauffer commented on app/Console/Commands/FetchProjectStats.php
> +
```suggestion
```

2020-10-15 18:30 UTC, mattstauffer commented on app/Console/Commands/FetchProjectStats.php
> +            $project->save();
Can we pull this into a protected method?

2020-10-15 18:30 UTC, mattstauffer commented on app/Console/Commands/FetchProjectStats.php
> +    public function getFilteredIssues($issues)
Can this instead be `filterIssues` and `filterPullRequests` since it's operating on something we pass in?

2020-10-15 18:30 UTC, mattstauffer commented on app/Console/Commands/FetchProjectStats.php
> +            return ! empty($issue->labels)
Would this work without the `empty`?

2020-10-15 18:30 UTC, mattstauffer commented on app/GitHub/GitHub.php
>  class GitHub
Would it make sense to rename this to `GitHubRepo` now or something like that? And we can rename the methods to remove the `project` prepend?

2020-10-15 18:30 UTC, mattstauffer commented on app/Project.php
> +        return Carbon::parse($this->updated_at)->diffForHumans();
Could we instead call the `diffForHumans` in the template and drop this method?

2020-10-15 18:30 UTC, mattstauffer commented on app/Project.php
> +        return $this->pull_requests->mapInto(PullRequest::class)->filter(function ($pullRequest) {
Are we mapping these, but not the non-old versions? Or am I missing where that is?

2020-10-15 18:30 UTC, mattstauffer commented on database/migrations/2020_09_28_230644_add_project_id_to_snapshots_table.php
> +            $table->bigInteger('project_id')->unsigned()->after('id');
Do we want a foreign key too?

2020-10-15 18:30 UTC, mattstauffer commented on database/seeds/ProjectsSeeder.php
> +            ->each(function($project) {
```suggestion
            ->each(function ($project) {
```

2020-10-15 18:30 UTC, mattstauffer commented on resources/views/dashboard.blade.php
> +        <meta name="twitter:site" content="{{ '@' . config('app.twitter') }}">
Geez! I thought I had caught all of these! 🤦🏻‍♂️

2020-10-15 18:30 UTC, mattstauffer commented on app/Console/Commands/CreateProjectSnapshots.php
> +                    'issue_count' => $project->issues->count(),
should we use the `issue_count` things or no? I guess not sure if it matters?

2021-01-17 17:37 UTC, mattstauffer commented
@jakebathman @AlexVanderbist I'm going to go back and implement the changes I proposed above, test this out, then merge, then I'll take a look at Alex's PR. Sorry for the several-month delay y'all, as I've mentioned in several other repos, life's just gotten away from me. :)

2021-01-17 18:06 UTC, mattstauffer commented
@jakebathman Thank you so much for your incredible work on this!

2021-01-17 18:07 UTC, merged