Port Ozzie to use Inertia
tighten/ozzie pull request #93
Opened 2021-02-19 16:30 UTC by jonsugar

## Individual project page

- Clicking the repository name on the dashboard no longer scrolls to the project. Instead a new 'repository page' opens.
- UI has been tidied up (in my opinion 🙈 ).
- The external icon has been replaced with the actual GitHub Icon.

![image](https://user-images.githubusercontent.com/1974648/108531715-ea05a500-72ce-11eb-931c-e542f5ea8290.png)

## PR View

The modal has been replaced with a page that anchors the PR in the context of its parent project. Notice the top of the page uses the same UI elements as the project page. With Inertia this means the transition between project page and PR and back again is slick.

![image](https://user-images.githubusercontent.com/1974648/108532033-4b2d7880-72cf-11eb-9623-7ee573ad9e9f.png)

## Issue View 🔥 

- Finally, you can now view issue descriptions from within Ozzie.
- Again, notice the re-use of UI elements.

![image](https://user-images.githubusercontent.com/1974648/108532209-85971580-72cf-11eb-8b03-86f2d5c510ec.png)

## Improvements to Markdown Parsing
- Integration of GitHubs own API for markdown parsing has solved some of the markdown rendering bugs that existed prior.
- Also, we can now bask in the glory of proper syntax highlighting in fenced code blocks 🎨 .

2021-03-09 03:34 UTC, mattstauffer requested changes
I made it through the first 43 files (up to `resources/ts/Pages/Projects/Show.vue`) but had to pause, figured I could leave the review now

2021-03-09 03:34 UTC, mattstauffer commented on resources/ts/Pages/Issue/Show.vue
> +            type: Object as PropType<Project>,
I've worked with TypeScript but not in Vue, so I'll have to just trust that this is written correctly :)

2021-03-09 03:34 UTC, mattstauffer commented on resources/ts/Pages/Projects/Index.vue
> +        organization: {
is this here to generate that hacktoberfest link?

2021-03-09 10:28 UTC, jonsugar commented on app/GitHub/Dto/PullRequest.php
> +    ///** @var \App\GitHub\Dto\Branch */
Yeah, it's a bit ugly... Short answer, No.

The DTO package uses that annotation to figure out what to hydrate the field with.

2021-03-09 10:35 UTC, jonsugar commented on public/js/317.js
> +(self.webpackChunk=self.webpackChunk||[]).push([[317],{5317:(e,t,a)=>{"use strict";a.r(t),a.d(t,{default:()=>f});var r=a(5166),o={class:"bg-white border-t-4 border-indigo relative z-10"},n={class:"ma
Those are the separate chunks produced by the code splitting during the build process. See, https://inertiajs.com/client-side-setup#code-splitting.

It's by no means 100% required but I think the best practice for a SPA.

2021-03-09 10:38 UTC, jonsugar commented on resources/ts/Pages/Issue/Show.vue
> +            type: Object as PropType<Project>,
Yeah, it's a bit of an odd one, I assume due to the way Vue is architectured 🤷‍♀️. See, https://v3.vuejs.org/guide/typescript-support.html#annotating-props

2021-03-09 15:02 UTC, mattstauffer commented on app/GitHub/Dto/PullRequest.php
> +    ///** @var \App\GitHub\Dto\Branch */
OK, but I assume it can't use that annotation if we have it commented out, right? I guess my note really is, "we should either un-comment these lines or delete them"

2021-03-09 15:03 UTC, mattstauffer commented on public/js/317.js
> +(self.webpackChunk=self.webpackChunk||[]).push([[317],{5317:(e,t,a)=>{"use strict";a.r(t),a.d(t,{default:()=>f});var r=a(5166),o={class:"bg-white border-t-4 border-indigo relative z-10"},n={class:"ma
👌🏻 sounds good. Thanks!

2021-03-09 15:03 UTC, mattstauffer commented on resources/ts/Pages/Issue/Show.vue
> +            type: Object as PropType<Project>,
Thanks!

2021-03-09 18:30 UTC, jonsugar commented on app/Http/Controllers/GithubIssueController.php
> +    protected function parseMarkdown(string $markdown): string
Done

2021-03-10 13:31 UTC, jonsugar commented on app/Http/Controllers/IssueController.php
> +            Cache::rememberForever(
Done

2021-03-10 13:31 UTC, jonsugar commented on app/Http/Controllers/ProjectController.php
> +            Cache::rememberForever(
Done

2021-03-12 12:39 UTC, jonsugar commented on resources/ts/Pages/Projects/Index.vue
> +        organization: {
yep

2021-03-12 13:18 UTC, mattstauffer commented on resources/ts/Pages/Projects/Index.vue
> +        organization: {
Sorry, I should've been more clear: you're passing in the organization to generate the link, but then not actually using it to generate the link. Could you update the code that's generating the link? Thanks!!

2021-03-12 13:47 UTC, jonsugar commented on resources/ts/Pages/Projects/Index.vue
> +        organization: {
Ha. I was confused there. I assumed you were referring to the actual hacktoberfest prop. Nevertheless, you are correct it's not used anymore—done.

2021-03-12 13:52 UTC, mattstauffer commented on resources/ts/Pages/Projects/Index.vue
> +                href="https://github.com/search?o=desc&amp;q=label%3Ahacktoberfest+is%3Aopen+type%3Aissue+user%3Atighten&amp;s=created&amp;type=Issues"
@jonsugar This is the spot where I thought you would want to use that organization field, since it's got `tighten` hardcoded in here

2021-03-17 13:10 UTC, jonsugar commented on resources/ts/Pages/Projects/Index.vue
> +                href="https://github.com/search?o=desc&amp;q=label%3Ahacktoberfest+is%3Aopen+type%3Aissue+user%3Atighten&amp;s=created&amp;type=Issues"
Done

2021-08-03 14:59 UTC, mattstauffer requested changes
Great freaking work! I did the best review I can as an only casual Inertia and TypeScript dev :)

2021-08-03 14:59 UTC, mattstauffer commented on app/Cache/CachedIssue.php
> +class CachedIssue
I like this Cache class idea! 🙌

2021-08-03 14:59 UTC, mattstauffer commented on app/GitHub/ParseMarkdown.php
> +        }
newline after please

2021-08-03 14:59 UTC, mattstauffer commented on app/Project.php
> +        return $this->issues->where('number', $id)->first() ?: abort(404);
Feels a little weird to abort instead of throwing an exception from within a model

2021-08-03 14:59 UTC, mattstauffer commented on composer.json
> +        "tightenco/duster": "0.3.0"
```suggestion
        "tightenco/duster": "^0.3.0"
```

2021-08-03 14:59 UTC, mattstauffer commented on resources/ts/components/GitHubItem.vue
> +        },
Can we start type and then required for all three?

2021-08-03 14:59 UTC, mattstauffer commented on resources/ts/components/GitHubItem.vue
> +    data(): Record<string, unknown> {
Why is the second unknown?

2021-08-03 14:59 UTC, mattstauffer commented on resources/ts/components/GitHubItem.vue
> +            :projects="[project]"
Nice

2021-08-03 14:59 UTC, mattstauffer commented on resources/ts/app.ts
> +// @ts-ignore
Just out of curiosity, what's being ignored here?

2021-08-03 14:59 UTC, mattstauffer commented on resources/ts/components/BreadCrumb.vue
> +        ozzieUrl(packageName: string): {vendor: string, name: string} {
Should we extract this? I think we have it on three components now?

2021-08-03 14:59 UTC, mattstauffer commented on resources/ts/components/GitHubLabel.vue
> +        getCorrectTextColor(hex: string): string {
Damn! OK!

2021-08-03 14:59 UTC, mattstauffer commented on resources/ts/components/GitHubListItem.vue
> +        projectName: {
Can we do type first, then required, like elsewhere?

2021-08-04 13:44 UTC, jonsugar commented on .eslintrc.js
> +module.exports = {
Yep, makes sense. Also, I've learned a lot since writing this. I've learned how to target rules better by having a root eslint config in the project home dir and more specific ones in, for example, `resources/js` and `resources/js/components. Also, by using an _overrides_ section you can target (or exclude) rules on a specific file(s) using globs. 

It's definitely worth looking at this...

2021-08-11 15:27 UTC, jonsugar commented on resources/ts/components/GitHubListItem.vue
> +        projectName: {
Done

2021-08-11 17:19 UTC, jonsugar reviewed
@mattstauffer thats a TypeScript built-in for a list of properties. So its basically saying...

`data()` is a function that returns an object with strings for keys and values that can be anything.  

```ts
data(): Record<string, unknown> {
        return {
            parsedGitHubItemBody: '',
            loaded: false,
        };
    },
```

Alternatively, we can be specific like so: 

```ts
data(): {parsedGitHubItemBody: string, loaded: boolean} {
        return {
            parsedGitHubItemBody: '',
            loaded: false,
        };
    },
```

That would get us autocompletion and a bit more type safety but at the expense of uglier code. As the scope of data is within the Vue SFC and we can see what properties are in there I'm not sure how much value we get from it.

Actually, we could remove the type declaration altogether but then TypeScript complains... it is TYPEScript after all 😆

2021-08-11 17:19 UTC, jonsugar commented on resources/ts/components/GitHubItem.vue
> +    data(): Record<string, unknown> {
@mattstauffer thats a TypeScript built-in for a list of properties. So its basically saying...

`data()` is a function that returns an object with strings for keys and values that can be anything.  

```ts
data(): Record<string, unknown> {
        return {
            parsedGitHubItemBody: '',
            loaded: false,
        };
    },
```

Alternatively, we can be specific like so: 

```ts
data(): {parsedGitHubItemBody: string, loaded: boolean} {
        return {
            parsedGitHubItemBody: '',
            loaded: false,
        };
    },
```

That would get us autocompletion and a bit more type safety but at the expense of uglier code. As the scope of data is within the Vue SFC and we can see what properties are in there I'm not sure how much value we get from it.

Actually, we could remove the type declaration altogether but then TypeScript complains... it is TYPEScript after all 😆

2021-08-11 17:21 UTC, jonsugar commented on resources/ts/components/GitHubItem.vue
> +    data(): Record<string, unknown> {
@mattstauffer thats a TypeScript built-in for a list of properties. So its basically saying...

`data()` is a function that returns an object with strings for keys and values that can be anything.  

```ts
data(): Record<string, unknown> {
        return {
            parsedGitHubItemBody: '',
            loaded: false,
        };
    },
```

Alternatively, we can be specific like so: 

```ts
data(): {parsedGitHubItemBody: string, loaded: boolean} {
        return {
            parsedGitHubItemBody: '',
            loaded: false,
        };
    },
```

That would get us autocompletion and a bit more type safety but at the expense of uglier code. As the scope of data is within the Vue SFC and we can see what properties are in there I'm not sure how much value we get from it.

Actually, we could remove the type declaration altogether but then TypeScript complains... it is TYPEScript after all 😆

2021-08-11 17:22 UTC, jonsugar commented on resources/ts/components/GitHubItem.vue
> +        },
done

2021-08-11 17:43 UTC, jonsugar commented on app/GitHub/ParseMarkdown.php
> +        $response = Http::post('https://api.github.com/markdown', ['text' => $markdown]);
Done

2021-08-11 17:43 UTC, jonsugar commented on app/GitHub/ParseMarkdown.php
> +        }
Done

2021-08-11 17:46 UTC, jonsugar commented on app/Cache/CachedProjectResource.php
> +        [$vendor, $name] = explode('/', $packagistName);
Done

2021-08-11 17:55 UTC, jonsugar commented on app/Cache/CachedProjectList.php
> +                    'hacktoberfest' => Carbon::now()->isSameMonth(Carbon::parse('October')),
Unless I've misunderstood the workflow, the stats:fetch artisan command is run to get the project data (on a schedule I assume). That means the data doesn't change until stats are re-fetched. Since I added `cache()->clear();` as the first thing the fetch command does, I think we are safe?

2021-08-11 17:57 UTC, jonsugar commented on app/Cache/CachedIssue.php
> +                $project = app(CachedProjectResource::class)("{$vendor}/{$name}");
Done

2021-08-12 00:34 UTC, mattstauffer commented on app/Cache/CachedProjectList.php
> +                    'hacktoberfest' => Carbon::now()->isSameMonth(Carbon::parse('October')),
OK, sounds good by me.

2021-08-12 00:37 UTC, mattstauffer commented on resources/ts/components/GitHubItem.vue
> +    data(): Record<string, unknown> {
OK, fair :) keeping it as is seems fine

2021-08-12 00:37 UTC, mattstauffer commented on app/Cache/CachedProjectResource.php
> +                return new ProjectResource(Project::forPackagist($packagistName)->firstOrFail());
Looks like this is my remaining question, and then we're good to merge!

2021-08-17 16:36 UTC, jonsugar commented on resources/ts/app.ts
> +// @ts-ignore
@mattstauffer I added that because there was an issue with the inertia TypeScript definition files that meant TypeScript was refusing to compile. This has since been fixed in newer versions of Inertia.

fixed in: 58007a7d33104062f9ba1f8c88e03dc2ee6d0564

2021-08-17 18:30 UTC, jonsugar commented on app/Project.php
> +        return $this->issues->where('number', $id)->first() ?: abort(404);
@mattstauffer fixed in  7bd9dd00418e12e99e8e2178319afe3e3a849001

2021-08-17 20:13 UTC, jonsugar commented on app/Cache/CachedProjectResource.php
> +                return new ProjectResource(Project::forPackagist($packagistName)->firstOrFail());
@mattstauffer if you are asking whether the ProjectResource is serializable, good question. I hadn't thought about that. It doesn't look like the Serializable interface is implemented in the Class Hierarchy of the ProjectResource so technically proper serialization is not guaranteed—as much as implementing an interface guarantees anything. I will say that _it works for me™_ 🤡. 

Having said all that, your point is totally valid so I've made some changes to explicitly serialize the data where appropriate. See, e24f38d273bb01d1a668d9e0f3f17f1679969f4a

2021-08-18 00:55 UTC, mattstauffer commented on resources/ts/app.ts
> +// @ts-ignore
Ahh, got it. Thanks!

2021-08-18 00:58 UTC, merged

2021-08-18 00:58 UTC, mattstauffer commented
Thanks so much @jonsugar!